# NumPy:
#### Numpy is a linear algebra library for python.

# Installation :
#### pip install numpy
#### conda install numpy

## NumPy Arrays :

#### Loading Dependencies

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
# one-dimensional array
arr = np.array(my_list)
arr 

array([1, 2, 3])

In [4]:
# two-dimensional array
my_mat = [[1, 2, 3],[4, 5,6], [7, 8, 9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# numpy range use function arange
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# we add step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# one-dimensional zeros
np.zeros(3)

array([0., 0., 0.])

In [9]:
# two-dimensional zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# one-dimensional one's
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
# two-dimensional one's
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# linspace return spaced no. over a specified interval.
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [14]:
# Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Random no.s 
np.random.rand(5)

array([0.52662931, 0.47281083, 0.11075403, 0.61170262, 0.65569822])

In [16]:
# random no. pick up two-dimensional matrix
np.random.rand(5,5)

array([[0.72538082, 0.98059403, 0.49542318, 0.32587849, 0.10754953],
       [0.23886591, 0.18436536, 0.32412866, 0.96290361, 0.57262194],
       [0.15209313, 0.51185363, 0.59569255, 0.20173011, 0.33397452],
       [0.07401078, 0.1470422 , 0.24012993, 0.36290723, 0.38727751],
       [0.64785668, 0.16309453, 0.12950158, 0.23561415, 0.11627409]])

In [17]:
# random two no. pick up
np.random.randn(2)

array([-0.87944662, -0.39499008])

In [18]:
# random four no. pick up in form of matrix
np.random.randn(4,4)

array([[ 1.08648179, -1.10515657,  0.67010255,  0.25263685],
       [ 0.06935823,  0.547615  , -3.00083527,  1.52758373],
       [-0.96090547,  0.04619253, -1.2057351 , -0.99069004],
       [-0.69346752, -1.64607473, -0.92505141, -1.88894942]])

In [19]:
# random one no. pick up
np.random.randint(1, 100)

33

In [20]:
# random ten no. pick up
np.random.randint(1, 100, 10)

array([29, 74,  5, 92,  4, 71, 54, 99, 64, 11])

In [21]:
# make array for 25 no.
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# random ten no. pick up
ranarr = np.random.randint(0,50,10)
ranarr

array([45, 44, 17, 40, 46,  0, 38, 37, 35, 16])

In [23]:
# reshape array into matrix
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr

array([45, 44, 17, 40, 46,  0, 38, 37, 35, 16])

In [25]:
# find max value
ranarr.max()

46

In [26]:
# find min values
ranarr.min()

0

In [27]:
# find index for max value
ranarr.argmax()

4

In [28]:
# find index for min value
ranarr.argmin()

5

In [29]:
# shape of one-dimensional vector
arr.shape

(25,)

In [30]:
# reshape 1d into 2d 
arr = arr.reshape(5,5)

In [31]:
arr.shape

(5, 5)

In [32]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
# find type of attribute
arr.dtype

dtype('int32')

In [34]:
from numpy.random import randint

In [35]:
randint(2,10)

3

# NumPy Indexing and Selection

In [36]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# indexing use []
arr[8]

8

In [38]:
# indexing from 1 to 5 return values
arr[1:5]

array([1, 2, 3, 4])

In [39]:
# return from 0 to 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [40]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
# all values use [:]
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# broadcast values
arr[:-5] = 100
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_copy = arr.copy()

In [48]:
arr_copy[:] = 100

In [49]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
# 2d array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
# slicing row and coloum
arr_2d[0][0]

5

In [53]:
# slicing entire row
arr_2d[0]

array([ 5, 10, 15])

In [54]:
arr_2d[2][1]

40

In [55]:
# [row, coloum]
arr_2d[2,1]

40

In [56]:
# row[:2] = 0 ,1 ;coloumn[1:] = 1, and soon 
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [58]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
# rreturn boolean values
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
# return boolean array values
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [61]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [62]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr_2d[:5,3:]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

In [64]:
arr_2d[1:4,2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

# NumPy Operations

#### Array with Array
#### Array with scalars
#### Universal Array Functions

In [65]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [69]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [70]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [71]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [72]:
arr / arr

C:\Anaconda3\envs\opencv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
1 / arr

C:\Anaconda3\envs\opencv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [74]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [77]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [78]:
arr.max()

10

In [79]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [80]:
np.log(arr)

C:\Anaconda3\envs\opencv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])